coverage:
  # Hold ourselves to a high bar
  range: 85..100
  round: down
  precision: 1

# Test files aren't important for coverage
ignore:
  - 'tests'

# Make comments less noisy
comment:
  layout: 'files'
  require_changes: true
