name: Crates.io Release

on:
  workflow_run:
    workflows: ["build-and-release"]
    types:
      - completed
  workflow_dispatch:
    
jobs:
  release-crates:
    name: Release crates.io
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        # We might need to wait some time between publishes
        - run: cargo publish -p siera-logger
        - run: cargo publish -p siera-agent
        - run: cargo publish -p siera-afj-rest
        - run: cargo publish -p siera-cloudagent-python
        - run: cargo publish -p siera-automations
        - run: cargo publish -p siera-cli
