name: E2E tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    name: E2E Test
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev
      - uses: actions/checkout@v3
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: deps
          cache-on-failure: true
      - name: Start acapy
        run: docker-compose -f ./docker/docker-compose.acapy.min.yml up -d
      - run: cargo test e2e_tests
