name: Clippy check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy

      - name: Clippy
        run: clippy
